### PR TITLE
Update SECURITY.md - broken link updated.

### PR DESCRIPTION
**Pull request by AhsenBaig**
#  #

## 🗣 Description ##
Changed the broken link from https://www.us-cert.gov/vulnerability-disclosure-policy to https://www.cisa.gov/vulnerability-disclosure-policy-template.

## 💭 Motivation and context ##

The other existing link needs to be fixed.

## 🧪 Testing ##

Click on the link, and you will see that it is broken.

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] All relevant type-of-change labels have been added.
- [X] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [X] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [X] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
Thanks for the fix @AhsenBaig!

What do you mean by "The other existing link needs to be fixed"?  I don't see another link to `us-cert.gov` in this repository.

**Review by mcdonnnj — CHANGES_REQUESTED** [review]
The new link is to a template file. We could arguably update the link to the [DHS VDP](https://www.dhs.gov/vulnerability-disclosure-policy) as there is a 404 from the current URL as it redirects to a [non-existent CISA page](https://www.cisa.gov/vulnerability-disclosure-policy).

**Comment by AhsenBaig** [comment]
Sorry I meant the original link: [CISA Vulnerability Disclosure Policy](https://www.us-cert.gov/vulnerability-disclosure-policy)
is broken. Updating it to what I believe is the correct one.

**Comment by jsf9k** [comment]
> The new link is to a template file. We could arguably update the link to the [DHS VDP](https://www.dhs.gov/vulnerability-disclosure-policy) as there is a 404 from current URL as it redirects to a [non-existent CISA page](https://www.cisa.gov/vulnerability-disclosure-policy).

I'll let @dav3r and @felddy weigh in.  I'm fine with the `cisa.gov` link, but maybe I'm missing something.

**Comment by jsf9k** [comment]
> > The new link is to a template file. We could arguably update the link to the [DHS VDP](https://www.dhs.gov/vulnerability-disclosure-policy) as there is a 404 from current URL as it redirects to a [non-existent CISA page](https://www.cisa.gov/vulnerability-disclosure-policy).
> 
> I'll let @dav3r and @felddy weigh in. I'm fine with the `cisa.gov` link, but maybe I'm missing something.

@dav3r explained to me the difference.  I'm very slow today. :disappointed:

**Review by jsf9k — APPROVED** [review]
Thank you @AhsenBaig!

**Review by dav3r — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]
Thanks @AhsenBaig for the original submission and thanks @jsf9k for updating the link.

**Pull request merged**
