### PR TITLE
Update the pull request template

### LINKED ISSUE #16: Update pull request template with pre- and post- approval checklists
# 💡 Summary #

As per discussion in https://github.com/cisagov/kali-packer/pull/57, we'd like to change `Checklist` to `Pre-approval checklist` and then also have templated text for post-approval and post-merge.

## Motivation ##

Sometimes, a PR requires work after it's merged. To make it easier to remember to do that work, we would like to include those tasks as checkboxes; however, we also prefer all checkboxes to be checked prior to review to indicate that it's ready.

As per discussion in https://github.com/cisagov/kali-packer/pull/57, we'd like to change `Checklist` to `Pre-approval checklist` and then also have templated text for post-approval and post-merge.

## Implementation notes ##

Example, as done by @jsf9k in the linked PR:

```
## ✅ Pre-approval checklist ##

...

## ✅ Post-approval checklist ##
- [ ] Task

## ✅ Post-merge checklist ##
- [ ] Task
```

Since this isn't applicable to most PRs, we may also want to make those checklists commented-out by default.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Title of checklist section has changed
- [ ] Additional checklist templates have been added

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR updates the pull request template that is used for the organization. The most notable change is moving from a single checklist to a multi-stage set of checklists.

## 💭 Motivation and context ##

We rarely use the `Screenshots` section so I believe we should just have it commented out by default over deleting it in the majority of PRs.

We often update the checklist to use a pre-approval/pre-merge/post-merge workflow as we've gotten better about versioning and have had to track dependency modifications needed for testing. This will help encourage that workflow for all pull requests in the future.

## 🧪 Testing ##

Automated tests pass.

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by hillaryj** [comment]
FYI Line 12 is missing a closing comment marker (it has been for a while, not a new change).

**Comment by mcdonnnj** [comment]
> FYI Line 12 is missing a closing comment marker (it has been for a while, not a new change).

Thanks for mentioning that ^^

**Review by jsf9k — APPROVED** [review]
Great improvements!

One thing I would like to see addressed is the octothorpe-wrapped comment at the very top of the PR template.  All that line does is add a pointless horizontal line at the top of the PR, which I find maddening.  We can't just remove the octothorpes, since then the linters complain that the first heading in the file isn't a first-level heading.  We need to do one of the following:
- Add _something_ to that first-level heading, but I can't think of anything meaningful.  The PR title is already handled by the PR web page, so it doesn't make sense to put it there.
- Make the other headings all first-level headings, but that looks terrible.

If nobody has any bright ideas I will just create an issue and we can punt on this one for now.

**Review by dav3r — APPROVED** [review]
Lovely! 🎯

**Comment by mcdonnnj** [comment]
> Great improvements!
> 
> One thing I would like to see addressed is the octothorpe-wrapped comment at the very top of the PR template. All that line does is add a pointless horizontal line at the top of the PR, which I find maddening. We can't just remove the octothorpes, since then the linters complain that the first heading in the file isn't a first-level heading. We need to do one of the following:
> 
>     * Add _something_ to that first-level heading, but I can't think of anything meaningful.  The PR title is already handled by the PR web page, so it doesn't make sense to put it there.
> 
>     * Make the other headings all first-level headings, but that looks terrible.
> 
> 
> If nobody has any bright ideas I will just create an issue and we can punt on this one for now.

@jsf9k I have no ideas at present so I created https://github.com/cisagov/.github/issues/31

**Pull request merged**
